### ISSUE TITLE
Enable Bitbucket Repositories

### ISSUE THREAD

**Issue by benniemosher** [thoughtbot/hound#1002]
I have a few repositories that are hosted on bitbucket.org and would like to be able to sign in to Bitbucket and include those on Hound. What are the oppositions or agreements to writing such an integration? Bitbucket has recently enhanced their hooks around Pull Requests and Commits, so it appears to have all the hooks that are needed for Hound.

**Comment by bronislav** [comment]
@teoljungberg already answered it in #827 

The only way that I see for such integration is to maintain it in separate fork.

**Comment by teoljungberg** [comment]
@bronislav - Is the integration at all possible? Does Bitbucket have all api endpoints required?

**Comment by bronislav** [comment]
AFAIK, they have required endpoints. They recently extended available endpoints for pull requests and commits and seems like now it is possible.

**Comment by bronislav** [comment]
@teoljungberg, I've just went through available endpoints and it seems that they (Bitbucket) have all required API calls.

**Comment by teoljungberg** [comment]
Could you share the link to their endpoint that would allow us to comment on a given file, on a specific line, at a given commit? I can't find it

**Comment by bronislav** [comment]
API v1 has such ability. [Link](https://confluence.atlassian.com/bitbucket/pullrequests-resource-1-0-296095210.html#pullrequestsResource1.0-POSTanewcomment).

**Comment by teoljungberg** [comment]
Ah, I was looking at the V2 API. Which is unforutinate, I imagine that Bitbucket will deprecate the V1 endpoints in favor of V2(or even V3).

**Comment by bronislav** [comment]
They only deprecate a few endpoints in V1 (only which have replacement in the V2)

**Comment by benniemosher** [comment]
I am going to close this issue since it appears that there was plenty of discussion on it in #827
