### ISSUE TITLE
Can my account act as a proxy for Hound?

### ISSUE THREAD

**Issue by gumatias** [thoughtbot/hound#1024]
This could be a total misunderstanding of my part on how hound is supposed to work, but thought it'd be worth asking here:

Is it possible to use my own account to make comments in Pull Requests instead of Hound?

Thanks!

**Comment by gylaz** [comment]
@gumatias Currently, there is no way to do that. Only @houndci user makes comments.

**Comment by gumatias** [comment]
Thanks @gylaz ! I'm thinking about forking the project and diving into this. 

From a high level, do you guys have any recommendations or insights on how one should go about implementing this feature in hound?

**Comment by gylaz** [comment]
If you fork and run your own, it should be easy to setup any user you want. In fact, all you have to do is set these two environment variables: https://github.com/thoughtbot/hound/blob/master/.env#L10-L11

The reason we make comments with @houndci only, is that it's clear that a bot is making the comments and not a user.
