### ISSUE TITLE
Houndci complains "Error parsing config for: jshint"

### ISSUE THREAD

**Issue by yyscamper** [thoughtbot/hound#1040]
Yesterday change my `.jshintrc` to fix the false alarm about `undefined variable` (see this PR:https://github.com/RackHD/on-core/pull/67), my change is to change "globals" to "predef" and enable the "mocha" in environment. That PR passes the houndci check, but houndci begins to complain about "Error parsing config for: jshint" in another PR (trigger houndci check after jshintrc change merging).

This is my problematic pull request:
https://github.com/RackHD/on-core/pull/66

All my change for .jshintrc in this pull request:
https://github.com/RackHD/on-core/pull/67/files

I tried other repos that still merged the same .jshintrc change, the new pull request against those repos still begin to report same error "Error parsing config for: jshint".

All repos worked well before that .jshintrc change.
Meanwhile, using the same .jshintrc, I try to do jshint check locally, all works well, so this should not due to the jshintrc format error.
```
jshintrc -c .jshintrc xxxx.js
```
My local jshint version is `v2.9.1-rc2`

**Comment by teoljungberg** [comment]
Hi @yyscamper, thanks for reporting the issue!

This has been resolved by https://github.com/thoughtbot/hound-jshint/pull/6. Which also is shipped to production.

Let me know if there's anything else you find, thank you!

**Comment by teoljungberg** [comment]
To give a bit of backstory, we changed the underpinnings of JShint recently to replace the old ruby gem we were using. Which now is backed by [hound-jshint](/thoughtbot/hound-jshint), and it uses a newer version of JSHint as a bonus.

**Comment by yyscamper** [comment]
Thanks @teoljungberg , very quick response and quick fix.

**Comment by yyscamper** [comment]
@teoljungberg : The same issue happens again, anything insight?

**Comment by teoljungberg** [comment]
@yyscamper We're leverage JSHint to do the parsing itself now, so it shouldn't be an issue anymore.

Feel free to reach out to our support at hound@thoughtbot.com so we can assist further.

**Comment by andela-fmustapha** [comment]
Hello Teoljungberg: I created a pull request recently and everything seems fine with my .hound.yml and eslintre.json files but I am getting the error 'Error parsing config for: eslint.'. Please could you advice me on what to do. Kindly follow the link below to view the PR.

[View PR](https://github.com/andela/kakashi-cfh/pull/31)

-Faith M.
