### ISSUE TITLE
Is it possible to tell which PRs hound should check?

### ISSUE THREAD

**Issue by gumatias** [thoughtbot/hound#1048]
The team I'm part of is currently split into sub-teams and we use GitHub's team feature. Is it possible to somehow tell hound to only scan PRs that has been tagged with @my-repo/my-team? 

We're currently experimenting with Hound and would love to disable it for other teams that are also working on the same repository as us. Thanks!

**Comment by gylaz** [comment]
There isn't a way in Hound to do that. It processes all open PRs.

**Comment by gumatias** [comment]
Got it. thanks!
