### ISSUE TITLE
Ruby style guide: "prefer reduce over inject"

### ISSUE THREAD

**Issue by mic-css** [thoughtbot/hound#1051]
The Ruby Style Guide states:
> Prefer map over collect, find over detect, select over find_all, reduce over inject and size over length.

but Hound is commenting:
> Style/CollectionMethods: Prefer inject over reduce. (https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size)

**Comment by gylaz** [comment]
Hound has opinionated defaults: https://github.com/thoughtbot/hound/blob/master/config/style_guides/thoughtbot/ruby.yml#L48-L54

We are working on removing this soon.

**Comment by spinlock99** [comment]
How can we override the default? I understand that implementing a new feature takes time but it would be very helpful if this issue pointed you to the documentation for how to resolve the issue.

Thanks.
