### ISSUE TITLE
Markdown linter not referenced in docs

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/hound#1072]
The markdown linter is referenced here https://github.com/thoughtbot/hound/blob/master/CONTRIBUTING.md#linters

But not here https://houndci.com/configuration

is that intentional?

**Comment by teoljungberg** [comment]
It is intentional. The markdown linter is still in an "alpha" phase, and we are battle-testing it internally. That's why it is not mentioned in the configuration documentation.

**Comment by teoljungberg** [comment]
Once it is considered stable, it will be documented along with the others.

**Comment by afeld** [comment]
An example @jessieay pointed out, just for reference:

https://github.com/thornco/dumb-ruby/pull/117

**Comment by teoljungberg** [comment]
I'm looping in @thorncp as he is the maintainer of the markdown linter

**Comment by GarthDB** [comment]
Remark is cool, but a ruby based tool like [markdownlint](https://github.com/mivok/markdownlint) is likely to work better with a jekyll blog.
