### ISSUE TITLE
Document how to use the Markdown linter

### ISSUE THREAD

**Issue by afeld** [thoughtbot/hound#1075]
I see it in

https://github.com/thoughtbot/hound/blob/master/CONTRIBUTING.md#linters

but not in

https://houndci.com/configuration

Curious about how to try it out!

**Comment by jessieay** [comment]
@afeld great minds https://github.com/thoughtbot/hound/issues/1072

**Comment by afeld** [comment]
Whoops, sorry, only looked through open issues.
