### ISSUE TITLE
Idea: Store config in guides

### ISSUE THREAD

**Issue by jferris** [thoughtbot/hound#293]
We're in a situation now where adding a new style guideline means:

1. Opening a pull request to guides.
2. Waiting a week for discussion.
3. Merging the pull request.
4. Opening a pull request to hound.
5. Reviewing, merging, and deploying that pull request.

In between steps 3 and 5, we get comments from Hound which conflict with our style guide.

It would be nice if:

* We had a config file in the guides repo.
* We could point Hound to it as our default config.
* Hound would somehow fetch updates for that config.

This way, we could update the config as part of pull requests which change the style guidelines. The guides and Hound will never be out of sync.

**Comment by salbertson** [comment]
@jferris, organization level configuration is something we are talking about adding. There has been talk of creating a UI in Hound to manage these style guides.

I think it would be pretty cool if Hound could use a gist or a file in a repo for each language.
