### ISSUE TITLE
Use JSCS in addition to JSHint for JavaScript linting

### ISSUE THREAD

**Issue by mrjoelkemp** [thoughtbot/hound#418]

**Comment by Adam262** [comment]
Hey there. Does Hound plan to support JSCS? I noticed in JSHint docs that they plan to deprecate many options relating to code style.

**Comment by thorncp** [comment]
It's pretty clear that JSHint alone isn't sufficient. There's been mentions of JSCS and ESLint (#738), but it's still undecided. Since they both have a dependency on Node, I don't think it's likely either of them will land until #727 is finalized and we can isolate the linters.

Quote from JSHint docs for http://jshint.com/docs/options/

> If you would like to enforce rules relating to code style, check out the JSCS project.

**Comment by thorncp** [comment]
The new service architecture has landed in Hound, so we now have the capabilities of linting with JSCS. Is there still interest for it? Would people prefer ESLint (#738)?

**Comment by codejet** [comment]
ESLint looks very good (traditional linting, style checking, JSX support...). Definitely interested in it (also having JSCS as an addition to JSHint if no ESLint).

**Comment by eidge** [comment]
+1 I'd definitely be interested!

**Comment by NewAlexandria** [comment]
Since [jsHint will stop checking for style](http://jshint.com/docs/options/#maxlen), something needs to be put in place.  I don't have more info yet to be any more opinionated than that.

**Comment by teoljungberg** [comment]
We are working on adding ESLint and JSCS alongside of JSHint. Stay tuned!

**Comment by meric426** [comment]
Great! +1 looking forward to JSCS

**Comment by teoljungberg** [comment]
If you guys are interested in trying out JSCS, it is now in beta!

If you want to try it out, please head over to https://houndci.com/configuration#jscs and see how to enable it.
Please contact us at hound@thoughtbot.com if you have any questions or feedback.

Happy linting!
