### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by kirs** [thoughtbot/hound#435]
Hey,
I'm willing to add golang support to Hound.

What do the maintainers think about it?

**Comment by salbertson** [comment]
Done, https://github.com/thoughtbot/hound/pull/852 and https://github.com/thoughtbot/hound-go.

@kirs thanks for the initial push for Go!

**Comment by kirs** [comment]
Wow, thanks!

**Comment by shurcooL** [comment]
This issue being closed leads me to think that there may be Go support (yay!), but the homepage does not:

![image](https://cloud.githubusercontent.com/assets/1924134/10229930/6f258512-682f-11e5-8d7f-d6a2e1f4ba5f.png)

Is Go officially supported?

**Comment by teoljungberg** [comment]
@shurcooL It's currently in beta, and you can activate it by adding:

```yaml
go:
  enabled: true
```

To your `.hound.yml`. Once it's considered stable, we'll officially document it

**Comment by gylaz** [comment]
Go has moved out of beta, and it should be reviewed by default.

**Comment by croaky** [comment]
Do we have icons/illustrations for the homepage for the new lingers out of beta? I think Lydia or Devon were working on them?
