### ISSUE TITLE
JS Indentation detection might be off

### ISSUE THREAD

**Issue by ZoharLiran** [thoughtbot/hound#438]
I'm getting the following comment although the indentation seems right:
![screen shot 2014-10-10 at 9 24 53 am](https://cloud.githubusercontent.com/assets/5846862/4595480/19af99c2-509a-11e4-8ec2-28c290b3bf9a.png)

This is throughout the whole repo and all of them seem right in the code.

**Comment by thorncp** [comment]
Is this still an issue? We updated JSHint in 331eecde, so I'm wondering if it's occurred since then. If not, I'm assuming it won't be fixed, since this linter has been [deprecated](http://jshint.com/docs/options/#indent).
