### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by mamachanko** [thoughtbot/hound#463]
That'd be great!

**Comment by 007lva** [comment]
:+1:

**Comment by Rscho314** [comment]
:+1:

**Comment by srt32** [comment]
What are the preferred python linting tools?

**Comment by tooxie** [comment]
I'd say [pep8](https://pypi.python.org/pypi/pep8) is the standard, but [flake8](https://pypi.python.org/pypi/flake8) wraps it and adds support for some other useful ones.

**Comment by mamachanko** [comment]
@srt32 [flake8](http://flake8.readthedocs.org/en/2.2.3/) does a pretty decent job out of the box

**Comment by salbertson** [comment]
Thanks to @jmcarp Hound now knows Python!

**Comment by tooxie** [comment]
Amazing! :+1:

**Comment by mamachanko** [comment]
@jmcarp @salbertson big stuff!
