### ISSUE TITLE
Errant unused method argument warning

### ISSUE THREAD

**Issue by Jberlinsky** [thoughtbot/hound#486]
When evaluating the following code, Hound raises an errant "unused method argument" flag:

    def distribute_scores(merit_points = Score::MERIT_POINT_DEFAULT)
        # Comments
        ways = group.users.count
        points_per_person = (merit_points / ways).round(2)
        # ... sic ...
    end

```Unused method argument - merit_points. If it's necessary, use _ or _merit_points as an argument name to indicate that it won't be used. You can also write as distribute_scores(*) if you want the method to accept any arguments but don't care about them.```

**Comment by gylaz** [comment]
This has been open a while without an update. Closing.
