### ISSUE TITLE
Question about supporting inherited_from

### ISSUE THREAD

**Issue by e2** [thoughtbot/hound#504]
Frustrating problem: can't locally replicate Hound's reported violations

Why? Because it's impossible to setup `.rubocop.yml` in such a way that both Hound and rubocop end up with the same configs.

Cause: Hound doesn't support Rubocop's 'inherited_from' (it's never processed)

Root cause: obviously, Hound doesn't use RuboCop's `ConfigLoader.load_file` because Hound doesn't work on physical files (since they are downloaded from github).

My question: what changes (if any) can I expect in the near future related to this? What kind of pull requests/workarounds would be acceptable (performance vs complexity vs effort)?

Here are some solutions I considered:

1) BEST SOLUTION - just show an error (somehow) when an `inherited_from` section is found in the custom rubycop.yml. The fact that Hound silently ignores 'inherited_from' (by avoiding any API which touches the FS) is *not* obvious, while having results different from `bundle exec rubocop` with no hint is just frustrating.

2) decent solution - custom implementation of 'inherited_from', which would pull missing files and properly load and merge them. (Also, this could help manage any style changes more predictably with version-specific defaults and/or overrides).

3) hacky solution - stubbing File.* and Dir.* calls (FakeFs?) and pulling files from GitHub when necessary - and using the `configuration_from_file` method.

4) unacceptable solution - pulling the files into a temporary directory - too messy, too slow and against Hound security policy

And the workaround for locally simulating a Hound check: "gluing" together the custom Rubocop for Hound from the custom Rubocop files.

While I doubt there is any major development planned for Hound, I do think it's wrong to silently ignore configuration options in a web app run triggered by a web hook.

**Comment by salbertson** [comment]
@e2, couldn't you move Ruby settings for Hound into another file, such as `.ruby-style.yml`, and inherit those settings from `rubocop.yml`?

As long as you update `.hound.yml` to use `ruby-style.yml` Hound should work and RuboCop should share Hound's settings for Ruby.

I could be missing something, let me know.

**Comment by e2** [comment]
@salbertson - the issue here is that inheritance is *silently* ignored by hound (which you can't debug without digging up and customizing code in Hound).

Hound is a hack to get RuboCop working without a filesystem - most users don't realize that (so it's not obvious that inheritance wouldn't be supported).

Inheritance is needed when using: https://github.com/bbatsov/rubocop#automatically-generated-configuration.

You need inheritance to support BOTH RuboCop's generated .rubocop_todo.yml and the style.

Please do checkout the functionality of: https://github.com/e2/hound-tools - which is basically a *huge* workaround around the lack of support for inheritance in Hound.

**Comment by lowjoel** [comment]
@salbertson My team (specifically, @jsyeo) was bitten by this for a few weeks and could not figure out why. I had to try various rounds of modifying my local rubocop.yml and pushing via a pull request until Hound seemed to respect my configuration. I had no clue why the settings I put in my config were ignored.

The root _root_ problem of this is that the defaults that Hound starts out with is _different_ from Rubocop's default (which is once again another gotcha). The problem I had was that I had a separate Rubocop config which does nothing except by _undoing_ Hound's defaults (restoring Rubocop's), and that was included by the Hound config (which contains project-specific settings)

At least some warning or message when this situation is found will be useful.

**Comment by e2** [comment]
@lowjoel - had the exact same frustration. 

I've been bitten by Hound (no pun intended) many times -  it's become less useful since it's stuck at RuboCop 0.25.0 (mostly because the parser silently crashes in Hound, and some false offenses are detected due to bugs in that RuboCop version).

Honestly, I wouldn't have used Hound if I knew the surprises I was in for - the extra time invested wasn't worth it (too much developer time spent trying to debug Hound by trial-and-error).

I'm not saying Hound needs to improve - I wouldn't know how to do a better job given the complications and restrictions. Everything is fine if you don't try and customize thing.

**Comment by salbertson** [comment]
@lowjoel @e2 I'm happy to announce that Hound now supports `inherit_from`, thanks to @jakecraige.

https://github.com/thoughtbot/hound/pull/717

**Comment by salbertson** [comment]
@e2 we are on RuboCop 0.29.1 now.

**Comment by salbertson** [comment]
I totally agree, not supporting `inherit_from` and not making it clear was not ideal and sorry it caused frustration. Thanks for all the feedback, we appreciate it and it really helps make Hound better.

**Comment by salbertson** [comment]
@lowjoel, do you think starting with nothing enabled in Hound by default, allowing you to enable what you needed would have helped in your case?

**Comment by lowjoel** [comment]
@salbertson That's great to know! I wasn't expecting `inherits_from` to be implemented. :+1:

I think Hound is a useful thing to have. Going back to Rubocop's defaults would make it a clear migration path from Rubocop (to Hound), but maybe the defaults specified in Hound's config could be enabled with a config parameter (in `hound.yml`, perhaps) and remove our need for `inherits_from`.

Maybe there might be a need for `inherits_from` still, because Rubocop inherits configuration settings up the directory tree, and I can imagine situations where that might be useful. For example, one might disable some cops for the `db/migrations` directory, and placing a Rubocop config file that inherits from parent directories just seem like the natural thing to do.

Once again, I'm not entirely sure this might be something that must be implemented, but at least some warning (maybe in the docs?) mentioning this gotcha might be useful

Thanks for Hound! It's reduced the level of noise from build failures.
