### ISSUE TITLE
houndci.com 404 page

### ISSUE THREAD

**Issue by Ashton-W** [thoughtbot/hound#515]
Not sure if website issues should be posted here.

`404`s look like this, wether from a mistyped url or a broken link
![screencapture at 17-12-2014-10_25_46](https://cloud.githubusercontent.com/assets/1650398/5464159/9dcc955c-85d8-11e4-983e-01631192368d.png)

This could be improved with a styled page with links to the homepage, etc.

**Comment by salbertson** [comment]
@frechg @donokuda, thoughts?

**Comment by frechg** [comment]
Yeah we could use some styled error pages.

**Comment by srt32** [comment]
Maybe something like this?

![image](https://cloud.githubusercontent.com/assets/2181356/6086143/58bbb4b8-adf4-11e4-8671-fa3cac16bec5.png)

**Comment by frechg** [comment]
hahaha nice!

**Comment by frechg** [comment]
Also kind of sad.

**Comment by frechg** [comment]
But I like the idea of building on that theme.

**Comment by Ashton-W** [comment]
No, that's perfect 🐶

**Comment by salbertson** [comment]
@frechg I'm merging https://github.com/thoughtbot/hound/pull/639, feel free to make the pages look nice or add some personality, ha.

**Comment by salbertson** [comment]
@Ashton-W thanks for opening an issue for this! Nicer error pages should be out today.
