### ISSUE TITLE
Enhancement: allow selecting Rubocop version

### ISSUE THREAD

**Issue by e2** [thoughtbot/hound#552]
How?
- having multiple RuboCop versions in `/vendor` (instead of locking in the Gemfile)
- changing each RuboCop's files to use a different namespace (e.g. using `sed` to change `module RuboCop` into e.g. `module RuboCop24`)
- allowing a version to be selected in `hound.yml`

Bonuses:
- since RuboCop version would be included, they could also include patches to better integrate with Hound
- each version could have a different style guide with no backward-compatibility issues
- the same idea could be applied to other linters (JS, Coffeescript, etc.)

**Comment by salbertson** [comment]
This has been brought up a few times, thanks for creating an issue. Our plan is to stick to the latest version of RuboCop as much as possible and not allow a version to be specified. We are currently using the latest, `0.29.1`.
