### ISSUE TITLE
SCSS Bugs

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/hound#562]
I enabled SCSS on Hound on a project and out of around 50 Hound comments, none have been a proper style violation. I ended up disabling SCSS on Hound for now…

95% of Hound’s comments have been about using `//` Sass-style comments (as opposed to CSS-style comments), but there are no comments in the code there:

![comments-1](https://cloud.githubusercontent.com/assets/903327/5704406/fa1b33f2-9a3e-11e4-82bd-0a2621e9dd14.png)
![comments-2](https://cloud.githubusercontent.com/assets/903327/5704408/fc47e026-9a3e-11e4-989b-aeb840cc451c.png)

I’ve also noticed Hound commenting about `margin` shorthand, but there is no use of `margin` here:

![margin](https://cloud.githubusercontent.com/assets/903327/5704416/1310d222-9a3f-11e4-8c72-a2d35ddc7957.png)

**Comment by kaishin** [comment]
Having the same issues highlighted above on a separate project.

**Comment by thorncp** [comment]
The fix for this is now in production. Please try it out!

**Comment by tysongach** [comment]
Woohoo! Thank you! I’ll give it shot.
