### ISSUE TITLE
Mediatyp constant removed in octokit v3.4.1

### ISSUE THREAD

**Issue by mbartmann** [thoughtbot/hound#568]
The constant PREVIEW_MEDIA_TYPE was removed in this [commit](https://github.com/octokit/octokit.rb/commit/7242f22de4bc2e4a837231b451a4d0ee057150ee) and hound deployments with newer octokit versions than v3.4.0 are crashing when running `RepoSynchronizationJob` in [this](https://github.com/thoughtbot/hound/blob/master/lib/github_api.rb#L7) line.

**Comment by gylaz** [comment]
How are you deploying Hound with newer octokit versions, since we have it locked in `Gemfile.lock`. Are you deploying some fork? I don't think this is a Hound issue, but I'm willing to help out.

**Comment by mbartmann** [comment]
Thanks for your quick response @gylaz and your offer to help :+1: 
I was deploying with capistrano on a different branch to a staging machine. Maybe the gems where updated there. As I didn't see any version specification of octokit in the `Gemfile`, I wanted to give you guys a heads up about the 'problem'.

**Comment by gylaz** [comment]
The master branch was updated to the latest Hound yesterday. Give that a try.
