### ISSUE TITLE
SCSS Wording

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/hound#574]
Hound notified me that I should better group/nest my Sass but it took me a while to figure out what he meant.

I think a message along the lines of “Next `select:focus` within `.select` on Line 6” would’ve been more clear to me.

![hound-wording](https://cloud.githubusercontent.com/assets/903327/5810728/f8f4f1a4-a018-11e4-99f5-9a87920f68e3.png)

**Comment by croaky** [comment]
If it said `“Nest select:focus within .select on Line 6”`, wouldn't it then be duplicating lines 22-24, at which point you'd want to merge with it?

It's a little weird that it picked the closing brace for the rule on lines 22-24, but it does seem to be correct.

**Comment by tysongach** [comment]
@croaky Yes! My bad; I mean `Line 22`. It is that Hound pointed to the closing bracket, rather than the opening one that tripped me up.
