### ISSUE TITLE
Is there some way to add new language styles for my projects?

### ISSUE THREAD

**Issue by gould** [thoughtbot/hound#585]
I saw the go-lang language addition PReq, and realise that currently you still have a lot of work that needs to be done before you have the time to add official support for other languages.

So, was wondering if there is a way to add custom language support in someway that does not require affecting your entire service and policies. 

I tried the adding a local server as described in the readme, but hit a wall when I got blocked by Heroku because of credentials, which I assume means that the local build instructions are intended for Thoughtbot employees.

**Comment by salbertson** [comment]
@gould, what credential issues did you run into?

**Comment by thorncp** [comment]
I wonder if that was [bin/setup](https://github.com/thoughtbot/hound/blob/ef65d0cbe0a81a676590824ee3151041b90629ec/bin/setup) trying to join the heroku apps and grab config. Those definitely would not work for non-thoughtbot folks, but I'm not sure if they'd error or not. Any update @gould?
