### ISSUE TITLE
github token gives too liberal access

### ISSUE THREAD

**Issue by ashleygwilliams** [thoughtbot/hound#597]
hiya! first off: cool product. i saw it and wanted to share it with my team.

HOWEVER, just to sign in, one is req'd to use github and provide read/write to all repos the user owns.

there are people on my team with ownership over the whole jquery CDN, among other less 'shareable', more 'sensitive' projects. they aren't keen on giving you access, even though they'd like to try out your product on other repos.

do ya'll have any thoughts on making the sign in access a bit more subtle?

thanks again for making and sharing this!

-a

**Comment by ashleygwilliams** [comment]
i also realize this could be a github issue, as well. but i'll leave this here anyways.

**Comment by salbertson** [comment]
Hi @ashleygwilliams! I'm glad you brought this up, others have asked about it as well.

Would a progressive approach to asking for access help in your case?

I'm thinking Hound could ask for access to public repos to being with, then once you are authenticated Hound would allow users to give more access based on organization.

Does that make sense?

**Comment by salbertson** [comment]
@ashleygwilliams, any thoughts on the approach I mentioned?

**Comment by rogierslag** [comment]
Same here, I'd like to give Hound access to some repos, but certainly not all private repositories. Even within an organization I'd like to make the access level a bit more fine grained than "you go girl!"

**Comment by jpalumickas** [comment]
I think this is an GitHub issue to not letting us choose to which private/organization repos give permissions.

**Comment by rogierslag** [comment]
You could opt to do it like eg Shippable and Codeclimate. They set a deploy token on the repository so you can access it

**Comment by salbertson** [comment]
Closing in favor of https://github.com/thoughtbot/hound/issues/701.

**Comment by salbertson** [comment]
@rogierslag that's a good idea. We are going to try out allowing users to opt into private repo access and see how that works for everyone.

**Comment by salbertson** [comment]
Hound now has optional private repo access. https://github.com/thoughtbot/hound/pull/900
