### ISSUE TITLE
Should Hound review commits outside of Pull Requests?

### ISSUE THREAD

**Issue by salbertson** [thoughtbot/hound#630]
Does your team not use Pull Requests? Would you like to see Hound review commits as well as Pull Requests?

**Comment by leenasn** [comment]
We follow mainline development, so does not follow pull requests, hence the request for supporting reviews on commits too.

**Comment by krasnoukhov** [comment]
That would be a nice addition for sure. We use PRs for major features and single branch for minor fixes/improvements, so having commits reviewed on that branch is the only thing we miss right now.

**Comment by hpurmann** [comment]
I would love to see ths. :yum:

**Comment by thorncp** [comment]
Closing in favor of #271, since it has more context.
