### ISSUE TITLE
Markdown lint tool

### ISSUE THREAD

**Issue by exalted** [thoughtbot/hound#650]
Could be interesting? https://github.com/mivok/markdownlint

**Comment by croaky** [comment]
We've been using this internally on some projects. It's good! Someday, it'd be great to add to Hound.

**Comment by salbertson** [comment]
Yes please. :+1:

**Comment by salbertson** [comment]
Is anyone interested in writing a Markdown service similar to https://github.com/thoughtbot/hound-scss and https://github.com/thoughtbot/hound-go? Now that we've nailed down the architecture we'd happily accept PRs for additional linters or languages.

**Comment by gylaz** [comment]
This is now live, but in beta. To enable, add the following to `.hound.yml`:

```yaml
markdown:
  enabled: true
```
