### ISSUE TITLE
Expand documentation to include explanation of configuration options

### ISSUE THREAD

**Issue by whmii** [thoughtbot/hound#736]
I was looking it to my hound configuration files and I was having a hard time figuring out what all the options (for scss) actually meant. I fount [this][1] very helpful. Perhaps it should be included in the documentation. Maybe just a link.

[1]:https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md

**Comment by salbertson** [comment]
@whmii feel free to open a PR, better documentation is always a good thing.

**Comment by thorncp** [comment]
Resolved by https://github.com/thoughtbot/hound-scss/pull/22

**Comment by whmii** [comment]
:+1:
