### ISSUE TITLE
Feature request: Add support for ESLint Javascript linter

### ISSUE THREAD

**Issue by kristerkari** [thoughtbot/hound#738]
Would be nice if optionally [ESLint](http://eslint.org/) could be used instead of JSHint. 

> The primary reason ESLint was created was to allow developers to create their own linting rules. ESLint is designed to have all rules completely pluggable. The default rules are written just like any plugin rules would be. They can all follow the same pattern, both for the rules themselves as well as tests. While ESLint will ship with some built-in rules to make it useful from the start, you'll be able to dynamically load rules at any point in time.

http://eslint.org/docs/about/

**Comment by rosschapman** [comment]
+1

**Comment by mikekreeki** [comment]
:+1:

**Comment by rupurt** [comment]
:+1:

**Comment by minasmart** [comment]
:+1: 

It has much nicer support for ES6, and JSX. It also actually parses the code using [espree](https://github.com/eslint/espree), which is actively maintained.

**Comment by chrislloyd** [comment]
:+1:

**Comment by teoljungberg** [comment]
We're very much aware that eslint is requested, and it is in our backlog. I'm locking this issue to avoid more :+1:'s

**Comment by salbertson** [comment]
Is anyone interested in writing an ESLint service similar to https://github.com/thoughtbot/hound-scss and https://github.com/thoughtbot/hound-go? Now that we've nailed down the architecture we'd happily accept PRs for additional linters or languages.

We could support something like this in `.hound.yml`:

```
javascript:
  enabled: true
  linter: eslint
```

**Comment by croaky** [comment]
I noticed Bootstrap switched from JSHint to ESLint in their v4 branch: http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by croaky** [comment]
Actually looks like it uses both ESLint and JSCS.

**Comment by hlascelles** [comment]
@salbertson I think you may have it now (written by yourselves?) https://github.com/thoughtbot/hound-eslint

We're using your paid-for hosted hound service, and would love to get this activated. Any idea when it might be fired up?

**Comment by teoljungberg** [comment]
Hi @hlascelles, It is indeed written by us. We're testing it out internally first to see if there are any kinks before rolling out a public beta. Which should happen soon. We'll get back to you once it does

**Comment by miksago** [comment]
@teoljungberg we'd also like to be involved in the public beta, for our medium sized code base at IDAGIO.com

**Comment by teoljungberg** [comment]
@miksago Glad to hear you're excited. Since it's a public beta, anyone can use it once we get there.

**Comment by miksago** [comment]
@teoljungberg well, in that case, consider us up for the private beta too :P

**Comment by alxndr** [comment]
@teoljungberg I'd also love to beta test ESLint with our hound account :tada:

**Comment by joejuzl** [comment]
+1

**Comment by teoljungberg** [comment]
We're still testing out the ESLint linter, and noticed a few kinks in it, which we now are working on. We're really close to getting it done. So stay tuned.

**Comment by BrandonMathis** [comment]
Thx for the update @teoljungberg. Looking forward to this :) Take all the time you need.

**Comment by teoljungberg** [comment]
I've got some exciting news for all of you who have waited for ESLint support - it is now in beta!

If you want to try it out, please head over to https://houndci.com/configuration#eslint and see how to enable it.
Please contact us at  hound@thoughtbot.com if you have any questions or feedback.

Happy linting!

**Comment by rupurt** [comment]
Awesome! Thanks @teoljungberg
