### ISSUE TITLE
SCSS lint bugs?

### ISSUE THREAD

**Issue by mdo** [thoughtbot/hound#742]
It appears we're seeing some inaccurate Hound errors in our SCSS linting over at https://github.com/primer/primer. We have a strict property order that's being reverse in a few instances. In addition, some lint config options appear to be ignored now.

Links to relevant PRs:

- PR for adding Hound and SCSS linter: https://github.com/primer/primer/pull/18
- Example of incorrect property order linting error: https://github.com/primer/primer/pull/19#discussion-diff-26996952
- Another inaccurate property order: https://github.com/primer/primer/pull/19#discussion-diff-27309061
- Example of ignored lint config option (I've disabled this test, but it's still running): https://github.com/primer/primer/pull/61#discussion-diff-27321517

I'm curious if this is because we haven't merged our `.scss-lint.yml` to `master` just yet? Until these PRs I hadn't seen any problems.

Here are some screenshots of those comment threads in case they go away with updates:

![screen shot 2015-03-27 at 12 52 44 pm](https://cloud.githubusercontent.com/assets/98681/6875961/7cc4b1cc-d480-11e4-83b5-21f44b8c4e16.png)
![screen shot 2015-03-27 at 12 52 57 pm](https://cloud.githubusercontent.com/assets/98681/6875963/7cc73546-d480-11e4-891a-f7d889adedf5.png)
![screen shot 2015-03-27 at 12 53 04 pm](https://cloud.githubusercontent.com/assets/98681/6875962/7cc5d9f8-d480-11e4-88d6-eb7b26764c2a.png)

**Comment by gylaz** [comment]
This should be resolved by https://github.com/primer/primer/pull/91.

**Comment by mdo** [comment]
Yup, my bad :sweat_smile:.
