### ISSUE TITLE
Hound never finishes

### ISSUE THREAD

**Issue by rupurt** [thoughtbot/hound#770]
Howdy,

Occasionally we have PR's that never complete their hound check. Do you have any tips for debugging as I'm not sure where to start?

We see the following message on our PR `Hound is busy reviewing changes...`

**Comment by JuanitoFatas** [comment]
+1. What info can be provided to help debug this issue?

**Comment by teoljungberg** [comment]
@rupurt Sorry for the late response, Reach out to us at `hound at thoughtbot dot com` with more details when it occurs and we'll take a look at it.

Thanks!

**Comment by rupurt** [comment]
Thanks @teoljungberg. It hasn't happened in the last week but I'll be sure to reach out if I see it again.

**Comment by hickscorp** [comment]
We're having this issue right now. Is there something we can do to get it unstuck?

**Comment by alexaivars** [comment]
we currently have 3 branches with stuck at "Some checks haven’t completed yet. 1 pending and 1 successful checks". Would like to share more but don't know how access any more info about the state of hound.

**Comment by gylaz** [comment]
Hound usually finishes within several minutes. If it looks "stuck" for longer, then it means the process crashed somewhere and we were never able to update the GitHub status. I'd recommend pushing a change to the branch/PR (or amending the last commit and force pushing up).
