### ISSUE TITLE
Hound asks for more permissions than it probably needs

### ISSUE THREAD

**Issue by evilaliv3** [thoughtbot/hound#776]
While working on [GlobaLeaks](github.com/globaleaks/GlobaLeaks) i've found that Hund would be a valuable tool to be integrated within the set of our on-commit CI and code quality metrics, but what from i'm viewing right know Hund is asking really for too much permissions and this prevents our adoption (https://github.com/globaleaks/GlobaLeaks/issues/1264).

![screenshot from 2015-05-09 21 22 10](https://cloud.githubusercontent.com/assets/217034/7551774/a3c763c8-f695-11e4-84ed-2e5b6e33747f.png)

[Landscape.io](https://landscape.io) that makes the same work using a python linter require really less and more precise permissions:
![screenshot from 2015-05-09 21 53 50](https://cloud.githubusercontent.com/assets/217034/7551795/142cbe88-f696-11e4-91a8-0885af66ac61.png)

with this i'm reopening the issue https://github.com/thoughtbot/hound/issues/98

**Comment by gylaz** [comment]
Thanks for the issue, but this is really something that is dictated by GitHub's permissions.

Landscape.io asks for less permissions to only pull in public information (repos, orgs) initially, but then it asks for more permissions for private stuff:
![screenshot 2015-05-11 11 14 09](https://cloud.githubusercontent.com/assets/116327/7571844/13dbde2a-f7cf-11e4-8af7-234c151f1a3d.png)
Hound just does it in one shot. We are considering splitting up the onboarding into two steps, similar to what Landscape.io does, but that still doesn't solve the underlying issue regarding the private repos.

**Comment by evilaliv3** [comment]
it's not a matter of granting visibility to private repositories. that is ok, i's a matter of allowing Hund to commit also (write access). this is not granted to landscape.io

if you open the arrow on Repositories (image that you pasted to me) you should se what i'm saying (if im not wrong, but i think not).

**Comment by evilaliv3** [comment]
this is the permissions i granted to landscape and it is able to work without issues:
![screenshot from 2015-05-11 20 36 25](https://cloud.githubusercontent.com/assets/217034/7572338/a4a7f116-f81d-11e4-8d94-7b8860998829.png)

**Comment by gylaz** [comment]
I am not sure what I'm missing:
![screenshot 2015-05-11 13 35 35](https://cloud.githubusercontent.com/assets/116327/7574507/ac1750b2-f7e2-11e4-9678-1f71b082b8fd.png)

**Comment by evilaliv3** [comment]
this is really strang, this is what i've granted to github on landscape: https://cloud.githubusercontent.com/assets/217034/7551795/142cbe88-f696-11e4-91a8-0885af66ac61.png

and it's able to work without problems. i think you are trying to use a different feature, maybe it's one needed for private repositories? mine is a public repository.
what are the actions you need to do that would require writing?

**Comment by gylaz** [comment]
It's a problem with how GitHub permission scopes. They don't have a "read-only" scope for private repos. It's full access to a repo, or nothing (unless it's public then anyone can read it).

The way some apps get around this GitHub issue is they have two applications. In the case of Landscape it's "Landscape.io" and "Landscape.io Pro" (see screenshots). The "Landscape.io Pro" app will have the read/write access to all repos (private and public). Like I've said, Hound just has one step of authentication, and we ask for the full package.

**Comment by evilaliv3** [comment]
thanks. this is exactly what i'm saying @gylaz.

in other worrd you are say, like i say, that given the fact the globaleaks is hosted on public repository, it would be possible to use Hund without granting any permission? if yes i would really thankful if you can poi me to the documentation that explains how to do that.

**Comment by gylaz** [comment]
> would be possible to use Hund without granting any permission

Unfortunately, that is not possible with Hound at the moment.

**Comment by evilaliv3** [comment]
k thanks anyway :) sadly we will need to way for such a possiblity :)
