### ISSUE TITLE
Feature request: delete comments after issue has been resolved

### ISSUE THREAD

**Issue by faun** [thoughtbot/hound#791]
It would be great if hound could delete its own comments after offending issues have been resolved. On a large pull request with many style issues, it can be overwhelming to manage all of the outstanding issues.

**Comment by gylaz** [comment]
Hi @faun,

Thanks for the request. We've been considering an possibility of removing comments, but that would mean we'd lose the history of comments. GitHub will collapse the comments if the line changes, thus practically reducing the noise.

On the other hand, I'm not sure that there needs to be any integrity in preserving the history of Hound comments, as they don't really serve any purpose besides pointing out the violations. Thoughts @thoughtbot/hound?

**Comment by thorncp** [comment]
I haven't personally run into any PRs where I felt overwhelmed by the number of comments on fixed lines, but it has been brought up before (#390). One potential concern would be the increased use rate of the API, but we should be able to use a user's token the vast majority of the time.

I think I'm neutral on this.

**Comment by faun** [comment]
Perhaps another solution would be to edit the comment and append some sort of emoji (or link to the commit that fixed the violation) to indicate that the violation has subsequently been fixed.

**Comment by teoljungberg** [comment]
I'm luke warm to this idea, the comments are already being collapsed as @gylaz said.

@faun If the comments were made by a person other than Hound, would you delete them aswell if the amount of comments were overwhelming? I wouldn't, it's a part of the code review process.

**Comment by faun** [comment]
Ok, I'm convinced. I think it's more of a configuration issue, having just added hound to an existing project.

**Comment by vaskaloidis** [comment]
Yeah I think this feature to delete all Houndbot comments should definitely be implemented - I mistakingly had Hound added as a CI service - apparently, before I really understood the extend of it's involvement... I did not think it would comment on every single line for this merge I just attempted... Extremely overwhelming / frustrating / annoying and now I think I am stuck with all of them..

I guess I should have done more research before adding Hound to my GH project. I really really love all the other Thoughtbot products / projects, so I assumed Hound would help keep contributors code clean - but the fact that it commented on every line-change of my commit is extremely annoying, and I wish there was a way to undo it.
