### ISSUE TITLE
Hound seems to ignore max_line_length setting in coffeescript_style.json

### ISSUE THREAD

**Issue by codejet** [thoughtbot/hound#792]
We just activated Hound and it raised a few "Line exceeds maximum allowed length" errors where the lines are shorter than the maximum we set. 

In the coffeescript_style.json we have the following:

```
  "max_line_length": {
    "level": "error",
    "value": 120
  }
```
And here an example of Hound complaining about a line which is only 95 characters long:

![screen shot 2015-06-08 at 11 02 53](https://cloud.githubusercontent.com/assets/802203/8031384/25612c80-0dce-11e5-9758-13363d51de2d.png)

I have seen that there was an issue like this before (https://github.com/thoughtbot/hound/issues/132), but it was resolved.

**Comment by paranoida** [comment]
Using `coffeelint` gem and running it from the console works fine though. No errors about max line length.

**Comment by Koronen** [comment]
I assume you have instructed Hound to [read `coffeescript_style.json` in `.hound.yml`](https://houndci.com/configuration#coffeescript)? Remember that both `coffeescript_style.json` and an updated `.hound.yml` need to be present in the PR branch for the new setting to take effect.

**Comment by codejet** [comment]
I just found the cause: the file names inside .hound.yml have dashes as separators while the actual files have underscores.

Sorry...

**Comment by salbertson** [comment]
@codejet, no problem. Thanks for letting us know and closing the issue.
