### ISSUE TITLE
Is there a limit of repos returned?

### ISSUE THREAD

**Issue by matthewford** [thoughtbot/hound#793]
I've a few repos which hound isnt finding,

**Comment by gylaz** [comment]
Are you an owner of the repos. Due to GitHub permission system, only repo owners can activate Hound for them.

**Comment by matthewford** [comment]
I think the issue is the github token is old - i've got a new org and it probably need reissuing to ask for approval?

**Comment by matthewford** [comment]
Found it - that org needed approval - did it via the github ui.

**Comment by gylaz** [comment]
Great!

For future reference, going to https://github.com/settings/applications, then clicking on "Hound CI" will display a list of organizations and Hound can be granted access via that screen.
