### ISSUE TITLE
Hound suggests renaming unused method arguments

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/hound#821]
Hound suggests renaming unused method arguments, e.g.:

> Unused method argument - `job`. If it's necessary, use `_` or `_job` as an argument name to indicate that it won't be used.

This isn't in the thoughtbot Ruby style guide. The closest thing in the guides is for block parameters:

> Use `_` for unused block parameters.

**Comment by gylaz** [comment]
I opened a PR for this https://github.com/thoughtbot/guides/pull/335.

**Comment by gylaz** [comment]
I'm thinking at the very least we want to be notified if a variable or argument is unused, because maybe someone forgot to remove it. Not sure if RuboCop supports a message to notify someone that something is unused.

**Comment by georgebrock** [comment]
There's a separate notification for an unused variable, and I agree that one makes sense. I'd also be happy with a “this argument is unused, did you mean to remove it?” notification. It's the “you should prefix this” part that I disagree with.

**Comment by gylaz** [comment]
This is now in the thoughtbot guides. Closing.
