### ISSUE TITLE
Triggering a recheck on a PR?

### ISSUE THREAD

**Issue by kjkuan** [thoughtbot/hound#840]
Is there a way to trigger a style check again without adding a new commit to a PR? Something like adding a specially formatted comment to the PR?

**Comment by gylaz** [comment]
There isn't.

The easiest way is to amend the last commit (which will cause it to become a new commit) and force push.

**Comment by gylaz** [comment]
There isn't.

The easiest way is to amend the last commit (which will cause it to become a new commit) and force push.
