### ISSUE TITLE
hash indentation message needs to be more descriptive e.g needs examples

### ISSUE THREAD

**Issue by ChrisCPO** [thoughtbot/hound#841]
I am constantly getting confused as to where hound wants indentations to be, usually with a hash.

Current message is confusing IMO. It would be awesome if examples were provided, I would submit a pr but I don't know what the correct answer is.

```ruby
def user_info
+      {
+         user_id: user.id
```
Use 2 spaces for indentation in a hash, relative to the start of the line where the left curly brace is.

Currently the spacing is two spaces from the start of the line where the left curly bracket is.

**Comment by teoljungberg** [comment]
From the example you provided, that's definately not 2 space left to the `{`

**Comment by thorncp** [comment]
The violation messages are coming from the linters directly; Hound doesn't modify them. You can submit a patch for the [message] in RuboCop to make it more clear and we'll pull it in when a new gem version ships.
[message]: https://github.com/bbatsov/rubocop/blob/4240ae468edbd1e1589ed3501cc16cbba3ab8513/lib/rubocop/cop/style/indent_hash.rb#L159
