### ISSUE TITLE
Puma?

### ISSUE THREAD

**Issue by beedub** [thoughtbot/hound#845]
Looks like your unicorn config is tailored for/from heroku. As they now recommend Puma over Unicorn, are you guys willing to switch? I'm open to pull requesting if so.

**Comment by gylaz** [comment]
A PR would be definitely welcome. We've done a lot of research in https://github.com/thoughtbot/suspenders/pull/501, so please have a look at it.

**Comment by croaky** [comment]
Closing in favor of https://github.com/thoughtbot/hound/pull/846. Thanks, @beedub!
