### ISSUE TITLE
Custom configuration

### ISSUE THREAD

**Issue by beedub** [thoughtbot/hound#847]
The docs mention adjusting `.hound.yml` to customize hound's settings. Because `.hound.yml` is checked-in to the repo, we'd have to commit changes to this file, which would create a permanent and undesired divergence between thoughtbot's mainline and our fork (I think?).

Comments in https://github.com/thoughtbot/hound/issues/576 (but those comments seem to be diverging from the original issue) have alluded to solutions that I think would address this issue, but not sure what the state of those solutions are.

**Comment by gylaz** [comment]
I'm not sure what your question or proposal is here.

**Comment by beedub** [comment]
The issue that I think I see (and am trying to confirm with this GH issue) is that the configuration (`.hound.yml`) is coupled to the hound app. If we wanted to customize our configuration for our dev team only, then we'd have to check-in the changes to our fork. If later we wanted to make an improvement to the hound app itself that we wanted to integrate with thoughbot's mainline, then we'd have to separate our config changes to `.hound.yml` from the app changes before pull requesting upstream. At best, it seems like a pretty cumbersome process.

After re-reading https://github.com/thoughtbot/hound/issues/576, I'll just close this and comment there instead

**Comment by gylaz** [comment]
I still am not sure I understand your concern.

If you are forking and modifying Hound, then it's expected that  you will differ from upstream, and will have to deal with any divergent merges.

If you want to tweak the default configuration on your fork you should be modifying files in https://github.com/thoughtbot/hound/tree/master/config/style_guides

**Comment by gylaz** [comment]
> then we'd have to separate our config changes to `.hound.yml` from the app changes before pull requesting upstream.

I see your concern now, but I don't think it's very difficult to reset to mainline upstream, then apply only the patches/commits that you want.

**Comment by beedub** [comment]
> I see your concern now, but I don't think it's very difficult to reset to mainline upstream, then apply only the patches/commits that you want.

Totally not that difficult, but given that hound is OS, I'd prefer not to have our fork diverge with any changes that aren't ever going to be merged upstream to thoughtbot's mainline. The suggestion in the other issue about storing overrides and configs in the database would address this issue for the most part though

**Comment by gylaz** [comment]
The db changes are the same as repo specific `.hound.yml`, only stored server-side.

You can just have `.hound.yml` in each of the repos that your fork is reviewing, then there would not need to be changes to your fork config.

**Comment by beedub** [comment]
Got it. We have dozens of private repos, so the db option seems like a better fit as it would only require one command to update all of them.

Thanks for the info!

**Comment by gylaz** [comment]
No problem.

To be clear, we didn't have the intention of moving the default configuration into the db, since that would make it slightly more difficult to upgrade linters.

**Comment by beedub** [comment]
Has the db stuff been merged into master yet? I can't find anything in the docs, and the closest thing that I see is the `style_guides` table, which isn't really being used in the code yet

**Comment by gylaz** [comment]
Nope, it hasn't been fully implemented yet.
