### ISSUE TITLE
Hound does not check rails require statements for javascript.

### ISSUE THREAD

**Issue by aeschylus** [thoughtbot/hound#849]
You can see an example of this behaviour here: https://github.com/sul-dlss/sul-embed/pull/269

Is there a way to integrate hound with rails asset pipeline so that these module invocations are considered valid?

**Comment by gylaz** [comment]
No, there is no way know what is required/imported.

You can whitelist well-know globals in the config. Example: https://github.com/thoughtbot/hound/blob/master/config/style_guides/javascript.json#L15-L16
