### ISSUE TITLE
No Style/Blocks lint in rubocop config

### ISSUE THREAD

**Issue by stereodenis** [thoughtbot/hound#851]
There is no `Style/Blocks` lint in [rubocop config](https://github.com/bbatsov/rubocop/blob/master/config/default.yml)
but Hound warns:
![showjet 2015-07-16 15-52-11](https://cloud.githubusercontent.com/assets/1406461/8723046/58204002-2bd3-11e5-927a-c3e23715b288.png)
```
bundle exec rubocop -v
0.32.1
bundle exec rubocop   
Warning: unrecognized cop Style/Blocks found in /Users/stereodenis/work/evrone/showjet/.rubocop.yml
```

**Comment by gylaz** [comment]
Hound uses own default configuration file. You can find it here: https://github.com/thoughtbot/hound/blob/master/config/style_guides/ruby.yml

**Comment by teoljungberg** [comment]
@stereodenis 

`Style/Blocks` has been removed between the version Hound is running and the latest rubocop version. There is #844 open for upgrading rubocop, which remedies this problem.
If you were to help out upgrading Rubocop for Hound, it would be most welcome

/cc @gylaz
