### ISSUE TITLE
Hund do require an excessive privilege set to be used on security conscious projects

### ISSUE THREAD

**Issue by fpietrosanti** [thoughtbot/hound#861]
This ticket is to refine the Hund security authorization footprint that it require w.t.r. to the opensource projects using it, like described on https://github.com/globaleaks/GlobaLeaks/issues/1264 .

An anonymous whistleblowing platform with strong encryption a high-security policy like GlobaLeaks, would be very happy to use it, if it has a less privileged set of authentication required to operate on the repositories.

It's just unreasonable to Write access to anything of the repositories using Hund. 

Anyone succesfully in hacking into the Hund's github account, would probably be able to backdoor hundreds or thousands of software projects.

**Comment by gylaz** [comment]
Part of this is that GitHub doesn't provide specific scopes (like read vs write) for private repositories. It's either all, or nothing. Thus, for private repos there is not much we can do, until this changes on GitHub's side.

We are in the process of allowing users to sign in and only see their public repos -- requiring almost no permissions. However, as soon as they want to enabled their private repos, we are back to square one, asking for read and write permissions to the repo.

**Comment by fpietrosanti** [comment]
@gylaz We'd love to start using Hund, and probably many security projects like CryptoCat or Mailvelope all using JS-encryption in sensible environment, when the privileges for uses with public repository will be reduced.

Hund it's a great products and i think it really need to expand among security developers, with those fix, it can happen!

Thanks for your job and for your commitment to the opensource community!

p.s. If you are coming to the CCC Hacker Camp 2015 in Germany, i'm happy to offer you a bottle of Italian Grappa and some nice locally done Espresso Coffee! :-)

**Comment by salbertson** [comment]
Here's the branch where this work is being done, https://github.com/thoughtbot/hound/tree/sa-github-scopes.

**Comment by salbertson** [comment]
Closing in favor of https://github.com/thoughtbot/hound/issues/701.
