### ISSUE TITLE
Cannot add Hound to public repository of an organization i'm member of of

### ISSUE THREAD

**Issue by fpietrosanti** [thoughtbot/hound#895]
Following #701 for public repository i've been trying to add Hound to the GlobaLeaks software https://github.com/globaleaks/globaleaks by using the "fpietrosanti" user that's one of the team member (owners) of the GlobaLeaks repository.

I don't see any way to add GlobaLeaks repository, part of "globaleaks" organization of which i'm part of:
<img width="1154" alt="screen shot 2015-08-22 at 11 09 30 am" src="https://cloud.githubusercontent.com/assets/770363/9423316/31346622-48bf-11e5-8938-2e26e0497de4.png">

<img width="1197" alt="screen shot 2015-08-22 at 11 09 47 am" src="https://cloud.githubusercontent.com/assets/770363/9423308/fa2dc2ea-48be-11e5-9b10-23356b9ace82.png">

**Comment by salbertson** [comment]
@fpietrosanti sorry about that. This was fixed by https://github.com/thoughtbot/hound/pull/900.
