### ISSUE TITLE
bump Rubocop version to 0.33

### ISSUE THREAD

**Issue by tansaku** [thoughtbot/hound#903]
Any chance we could bump the Rubocop version to the latest? i.e. 0.33.  From the Gemfile it looks like hound is on "0.29.1"

There are various config options in 0.33 such as DisabledByDefault, which I think might help us get round the various confusions arising from the way in which hound overrides the rubocop settings in each project:

https://github.com/thoughtbot/hound/issues/576

Many thanks in advance

**Comment by Koronen** [comment]
There's an open PR for this, see #844.

**Comment by gwright** [comment]
Unfortunately #844 has been closed.  It seems like the attempt to bump Rubocop to 0.33 got mixed in with other changes to the configuration mechanisms.

:+1: to have an update that just bumped Rubocop without dealing with any of the other configuration changes.

**Comment by tansaku** [comment]
@Koronen since that pull request has been closed, is there now some other pathway whereby hound will start using the latest version of rubocop (now 0.34.1)
