### ISSUE TITLE
using image_url in css. 

### ISSUE THREAD

**Issue by samirchian** [thoughtbot/hound#904]
![image](https://cloud.githubusercontent.com/assets/7979308/9525487/2ea678c2-4c99-11e5-9488-5364c200d9e9.png)

**Comment by gylaz** [comment]
This is likely an `scss-lint` bug. Can you verify if you get this by running the `scss-lint` linter?

**Comment by samirchian** [comment]
app/assets/stylesheets/sections/_report.scss:109 [W] NameFormat: Name of function `image_url` should be written in all lowercase letters with hyphens instead of underscores @gylaz  you are right I got it when I run scss-lint.

**Comment by samirchian** [comment]
https://github.com/brigade/scss-lint/issues/567

**Comment by gylaz** [comment]
Looks like it's a real warning and is configurable. Closing.
