### ISSUE TITLE
Link to each of the linters from the README or CONTRIBUTING doc

### ISSUE THREAD

**Issue by croaky** [thoughtbot/hound#911]
So people can better see the architecture and know where to contribute or learn from.

**Comment by Alehanz** [comment]
Hi there!

I'd like to do this one if that's okay. However, I do have a couple of questions.

Should the links go directly to the linters' github repos mentioned here: https://houndci.com/configuration ? 
Also, should the default configs be linked to as well?

So far I was planning on adding those links to the CONTRIBUTING.md right after the testing section.

Thanks!

**Comment by gylaz** [comment]
Either the GitHub project page or the linters site would work. Sometimes the sites provide more information than the GitHub page. On the other hand, always linking to GitHub page is consistent.

Also, I think the default configs would be useful.

**Comment by teoljungberg** [comment]
@Alehanz feel free to take the reigns on this

**Comment by Alehanz** [comment]
@gylaz I'll stick with the GitHub pages then, for the sake of consistency. Will also include the default configs.

@teoljungberg Great, thanks!

Pull request on its way.

**Comment by croaky** [comment]
Thanks!
