### ISSUE TITLE
Hound comments contradictory CSS violations with hexadecimal values represented with letters

### ISSUE THREAD

**Issue by MariaCheca** [thoughtbot/hound#934]
Pushing to my PR branch a change in a CSS file, for example:
```
.myStyle {
  color: #AAAAAA;
  font-style: italic;
}
```
Hound comments:
> Color literals like #AAAAAA should only be used in variable declarations; they should be referred to via variable everywhere else.
Color `#AAAAAA` should be written as `#aaaaaa`

After making the changes it suggests and changing the hexadecimal representation to lowercase, Hound comments again:

> Color `#aaaaaa` should be written as `#AAAAAA`

Seems like there's no clear difference between which representation is better :)

**Comment by thorncp** [comment]
@MariaCheca Is the repo public? If not, do you have any custom configuration you can share?

**Comment by thorncp** [comment]
Oh, I see you provided on in Slack. Pardon my laziness.

**Comment by thorncp** [comment]
@MariaCheca It looks like [pulling in master](https://github.com/CartoDB/cartodb/commit/35be1fced9c3221114b5eac44b83615069297953) part way through your PR introduced SCSS-Lint config changes, which led to the different violations. I think you should be ok addressing reported violations moving forward. :arrow_right:
