### ISSUE TITLE
Hound comments contradictory CSS violations with single/double quotes

### ISSUE THREAD

**Issue by MariaCheca** [thoughtbot/hound#935]
Could be related with #934 
Pushing to my PR branch a change in a CSS file, for example:
```
.myStyle {
  content: '1';
}
```
Hound comments:
> Prefer double-quoted strings

After making the changes it suggests and changing from single to double quotes, Hound comments again:

> Prefer single quoted strings

**Comment by thorncp** [comment]
@MariaCheca It looks like [pulling in master](https://github.com/CartoDB/cartodb/commit/35be1fced9c3221114b5eac44b83615069297953) part way through your PR introduced SCSS-Lint config changes, which led to the different violations. I think you should be ok addressing reported violations moving forward. :ok_hand:
