### ISSUE TITLE
Upgrade scss-lint

### ISSUE THREAD

**Issue by peterlind** [thoughtbot/hound#959]
Hey, what version of `scss-lint` are you using? Seems it's before https://github.com/brigade/scss-lint/commit/a2ddd6853b624865ff2e9cfe277f0fd994253caa since I'm getting 

<img width="950" alt="screenshot 2015-10-12 15 10 13" src="https://cloud.githubusercontent.com/assets/151010/10429329/f4743b48-70f7-11e5-8f8d-f23ecd773323.png">

The configuration option `camel_case` is interpreted as a regex instead of a valid option. Plz upgrade if possible :pray:

**Comment by Koronen** [comment]
```rb
gem "scss-lint", "0.34.0"
```

https://github.com/thoughtbot/hound-scss/blob/531abf4e6bf41dcfd8e6bb44a760306d4f776091/Gemfile#L7

**Comment by peterlind** [comment]
Oh, it was in a separate repo. Can haz `>= 0.37.0` ?

**Comment by teoljungberg** [comment]
ScssLint currently is troublesome to upgrade, we're working the upgrading process currently by moving away from having a default configuration.

**Comment by peterlind** [comment]
Thanks for input. I'll disable the check in our repo until you have upgraded

**Comment by thorncp** [comment]
Are we still blocked by https://github.com/brigade/scss-lint/issues/435 ? Should we seek an alternative solution at this point?

**Comment by teoljungberg** [comment]
This is upgraded as of now. I hope this solves your issue @peterlind

Referenced PR: https://github.com/thoughtbot/hound-scss/pull/17

**Comment by peterlind** [comment]
Thanks all! It works now
