### ISSUE TITLE
Hound ignores? rubocop config files that use inherit_from

### ISSUE THREAD

**Issue by dkapadia** [thoughtbot/hound#967]
Recently our ruby configuration seems to be ignored by hound, though previously it worked fine. I've set up an example repo that shows the same problem here: 

https://github.com/dkapadia/hound-test/pull/1

Our setup is pretty simple, a [.rubocop.yml](https://github.com/dkapadia/hound-test/blob/master/.rubocop.yml) file that inherits_from [hound's defaults] (https://github.com/dkapadia/hound-test/blob/master/.rubocop_hound.yml) and overrides whatever cops that we have for our project. 

In this test repo, I've overridden a single cop to change the LineLength from the default of 80 to 100. In the PR linked above I would expect hound to not comment, since the line being added is 100 characters long, but instead it does raise a violation and includes the incorrect max count of 80 in the comment.

It's possible that the issue is the `inherit_from` configuration, that used to be explicitly tested/supported in hound, but perhaps that was removed accidentally in this commit: https://github.com/thoughtbot/hound/commit/fec130bfe8f411c22681cfe74f7cfd133c3b5ca4 ?

Would love to see this fixed as it currently means we're ignoring all hound comments on our project (too many false positives).

**Comment by tansaku** [comment]
I think we may be having the same issue

**Comment by teoljungberg** [comment]
Thanks for reporting the issue, this was an unintentional regression made in fec130b.

**Comment by tansaku** [comment]
thanks @teoljungberg - I'm noticing what seems like a related issue, which is that I get no hound comments unless I include enabled true in my hound config like so:

```yml
ruby:
  config_file: .rubocop.yml
  enabled: true
```

**Comment by teoljungberg** [comment]
@tansaku The issue you're experiencing should be resolved by #970.

@dkapadia We re-added support for `inherit_for` in #97 (not yet merged)

**Comment by teoljungberg** [comment]
@dkapadia The issue with `inherit_from` is now resolved. Thanks for your patience!
Let us know if there's anything else acting up.
