### ISSUE TITLE
Empty .rubocop_todo.yml crashes houndci

### ISSUE THREAD

**Issue by sdellenb** [thoughtbot/hound#983]
#### Description
If a rubocop config file included with ```inherit_from``` contains no entries except comments, houndci crashes with
> Error parsing config file: .rubocop.yml. Click "details" for assistance."

#### Steps to reproduce
1. Create a new .rubocop.yml config file and include it from .hound.yml
2. Use rubocop to generate .rubocop_todo.yml by running ```rubocop --auto-gen-config``` and add ```inherit_from .rubocop_todo.yml``` to .rubocop.yml ([link to sample commit](https://github.com/sdellenb/hound-test/commit/dd76a7fa68d7fea0142568211d97d6b4bd80bfd0))
3. Fix remaining offenses bit by bit and run ```rubocop --auto-gen-config``` before commit to get an updated .rubocop_todo.yml.
4. Once all offenses are fixed, .rubocop_todo.yml will only contain the generated comment header

#### Result
* houndci crashes with  
> Error parsing config file: .rubocop.yml. Click "details" for assistance."

#### Expected Result
* houndci should gracefully skip empty files while merging configs, since in this particular case the file is auto-generated.
* rubocop has no problem with the included file being empty

#### Sample link
I've set up a pull request where the issue occurs in the last commit: https://github.com/sdellenb/hound-test/pull/3

**Comment by teoljungberg** [comment]
This is one of the best bug reports I have ever received.
Thank you!

You're indeed right, Hound should not be any different than Rubocop in form of its configuration.

**Comment by teoljungberg** [comment]
@sdellenb Thanks for reporting this to us. It's now fixed and deployed

**Comment by alxndr** [comment]
Just saw this error happening on a tiny project with an empty `.rubocop.yml` file.
