### ISSUE TITLE
Rubocop ignore rules

### ISSUE THREAD

**Issue by croaky** [thoughtbot/hound#986]
@pustovalov I'm pulling this out of email so the Hound team can see it:

> Hey guys, 

> I installed rubocop to local environment and indicated this rule:

> Metrics/LineLength: false

> https://github.com/pustovalov/app/blob/master/.ruby-style.yml#L543

> Rubocop show this:

```
false: 52 files inspected, 86 offenses detected
true: 52 files inspected, 114 offenses detected
```

> But hound still send me a messages about long line:

> https://github.com/pustovalov/app/pull/13#discussion_r43354062

> My config file for Hound:
> https://github.com/pustovalov/app/blob/master/.hound.yml

**Comment by pustovalov** [comment]
@croaky thx

**Comment by gylaz** [comment]
The comment is made by the HAML linter. Try setting https://github.com/brigade/haml-lint/blob/master/lib/haml_lint/linter/README.md#linelength.

**Comment by pustovalov** [comment]
@gylaz I made this:
https://github.com/pustovalov/app/commit/71c43bf471366da98290d631ef131c6f4d0c9b28

And still can see error from hound:
![](https://monosnap.com/file/K4S4ra7HhpjwPOWiC0wZMZ20pDTTG9.png)

**Comment by umerkulovb** [comment]
Joining this thread, looks like hound is failing when rubocop is enabled for `.haml` files. 
My hound config is here:

![image](https://cloud.githubusercontent.com/assets/1033021/12567859/aa6204c8-c38f-11e5-8738-d82bfd28bd97.png)

![image](https://cloud.githubusercontent.com/assets/1033021/12567871/b839385a-c38f-11e5-8940-fb5e42f29007.png)


And I intentionally made a change to get warning:
![image](https://cloud.githubusercontent.com/assets/1033021/12567895/e193f9ba-c38f-11e5-8fc7-6ca1f85d76de.png)


However, I'm getting an error message about hound completely failing reviewing this PR

**Comment by teoljungberg** [comment]
@umerkulovb Could you contact us at `hound@thoughtbot.com` with the contents of your `.hound.yml`, along with `.haml-style.yml`? And we'll take it from there

**Comment by teoljungberg** [comment]
@pustovalov If you also could contact us via our support email, we'll see what we can do about your issue to
