### ISSUE TITLE
upgrade rubocop to 0.35.1

### ISSUE THREAD

**Issue by tansaku** [thoughtbot/hound#994]
There's a new version of rubocop out - what's the process for upgrading hound to that?  Does it require a pull request?

**Comment by thorncp** [comment]
@tansaku It does require a PR. In a hand-wavy sense, the process is to update the gem and make sure the test suite passes. We like to do a solid round of testing in our staging environment when that happens, which does add some time. I'll try to get to this soon and will post updates here.

**Comment by tansaku** [comment]
thanks @thorncp - is this something I can do myself?  Or you need it to be done internally by you guys?

**Comment by thorncp** [comment]
You can submit a PR if you're interested! We'll still handle the smoke testing.

**Comment by BenMorganIO** [comment]
I think we should update to 0.36. Hound is currently signalling errors when using the `&.` syntax.

**Comment by teoljungberg** [comment]
@BeckyDunbar We should, but the upgrade to 0.36 is not straight forward. We are working on paving out a way for it

**Comment by gylaz** [comment]
https://github.com/thoughtbot/hound/pull/1034 upgrades RuboCop to 0.36.0.
