### ISSUE TITLE
rubocop:disable comments not supported

### ISSUE THREAD

**Issue by winkler1** [thoughtbot/hound#995]
I've setup Rubocop locally with Guard for faster feedback, and it respects the comments-

 ```   
 if raise_if_error && result.size > 0
      # rubocop:disable Rails/Output
      puts "---- JSON SCHEMA -----"
      ap schema
      raise result.to_s
    end
```

... but Hound is still complaining about the issue on the PR.

These pragmas are super useful in documenting intent, and filter out noise locally. Would be really nice for Hound to respect them.

**Comment by jurre** [comment]
I believe that hound *used* to respect these, but it has stopped doing so recently. If anyone could point me in the right direction I'd be happy to contribute a fix (if this is indeed desired).

**Comment by teoljungberg** [comment]
Thanks for reporting this, it is indeed strange that it stopped working.
I need some more information to reproduce the issue, I would need answers to these questions:
- Are you using the default configuration? If not - could you share you config with me?
- Is it enough to reproduce the issue to only have a file that has this content:
```ruby
# rubocop:disable Rails/Output
puts "---- JSON SCHEMA -----"
```

**Comment by jwfearn** [comment]
I am seeing this too.  Disables used to work fine but they stopped working weeks ago.  It's pretty annoying.

**Comment by jwfearn** [comment]
Here's a test file called `t.rb` where Hound fails to honor rubocop:disable:

```rb
t = 1447542833 # rubocop:disable Style/NumericLiterals
puts(t) # rubocop:disable Rails/Output
```

Error reported in GitHub with Hound:
![image](https://cloud.githubusercontent.com/assets/276996/11484089/10c3db3e-9761-11e5-9b6a-4f0bb836360c.png)

**Comment by thorncp** [comment]
I think #1000 (:one: :zero: :zero: :zero: :bangbang: :confetti_ball:) should address this.

**Comment by jurre** [comment]
:tada: thanks!
